// =============================================================================
// server.go — gRPC service implementation for the Task Board
// =============================================================================
//
// This file implements the TaskBoardServiceServer interface generated by
// protoc-gen-go-grpc. It handles all RPCs defined in taskboard.proto:
//
//   - GetBoards:   List all boards (unary)
//   - GetBoard:    Get a single board with columns and cards (unary)
//   - CreateCard:  Add a new card to a column (unary)
//   - MoveCard:    Move a card between columns (unary)
//   - DeleteCard:  Remove a card (unary)
//   - WatchBoard:  Stream board updates in real-time (server streaming)
//
// The server uses an event-bus pattern (channels) for the WatchBoard streaming
// RPC, allowing multiple clients to observe changes simultaneously.
// =============================================================================

package main

import (
	"context"
	"fmt"
	"log"
	"sync"

	pb "backend-grpc/pb"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ---------------------------------------------------------------------------
// TaskBoardServer — implements pb.TaskBoardServiceServer
// ---------------------------------------------------------------------------

// TaskBoardServer provides the gRPC service implementation for task board operations.
type TaskBoardServer struct {
	pb.UnimplementedTaskBoardServiceServer

	store *Store

	// watchers tracks active board watchers for the streaming RPC.
	// Key: board_id, Value: slice of channels that receive updates.
	watchersMu sync.RWMutex
	watchers   map[string][]chan *pb.BoardUpdate
}

// NewTaskBoardServer creates a server with a pre-seeded in-memory store.
func NewTaskBoardServer() *TaskBoardServer {
	return &TaskBoardServer{
		store:    NewStore(),
		watchers: make(map[string][]chan *pb.BoardUpdate),
	}
}

// ---------------------------------------------------------------------------
// GetBoards — returns all boards (unary RPC)
// ---------------------------------------------------------------------------

// GetBoards returns a list of all available boards.
// In a real app, this might support pagination via metadata.
func (s *TaskBoardServer) GetBoards(ctx context.Context, req *pb.Empty) (*pb.BoardList, error) {
	log.Println("[GetBoards] Fetching all boards")

	boards := s.store.GetAllBoards()
	return &pb.BoardList{Boards: boards}, nil
}

// ---------------------------------------------------------------------------
// GetBoard — returns a single board by ID (unary RPC)
// ---------------------------------------------------------------------------

// GetBoard returns a single board with all its columns and cards.
func (s *TaskBoardServer) GetBoard(ctx context.Context, req *pb.BoardRequest) (*pb.Board, error) {
	log.Printf("[GetBoard] board_id=%s\n", req.BoardId)

	board := s.store.GetBoard(req.BoardId)
	if board == nil {
		// Use gRPC status codes instead of generic errors
		return nil, status.Errorf(codes.NotFound, "board %q not found", req.BoardId)
	}

	return board, nil
}

// ---------------------------------------------------------------------------
// CreateCard — adds a card to a column (unary RPC)
// ---------------------------------------------------------------------------

// CreateCard creates a new card in the specified board/column.
func (s *TaskBoardServer) CreateCard(ctx context.Context, req *pb.CreateCardRequest) (*pb.Card, error) {
	log.Printf("[CreateCard] board=%s column=%s title=%q\n", req.BoardId, req.ColumnId, req.Title)

	// Validate required fields
	if req.Title == "" {
		return nil, status.Error(codes.InvalidArgument, "title is required")
	}
	if req.BoardId == "" {
		return nil, status.Error(codes.InvalidArgument, "board_id is required")
	}
	if req.ColumnId == "" {
		return nil, status.Error(codes.InvalidArgument, "column_id is required")
	}

	card, err := s.store.CreateCard(req.BoardId, req.ColumnId, req.Title, req.Description)
	if err != nil {
		return nil, status.Errorf(codes.NotFound, err.Error())
	}

	// Notify watchers about the new card
	s.notifyWatchers(req.BoardId, "card_created")

	return card, nil
}

// ---------------------------------------------------------------------------
// MoveCard — moves a card to a different column/position (unary RPC)
// ---------------------------------------------------------------------------

// MoveCard relocates a card to a target column at a specific position.
func (s *TaskBoardServer) MoveCard(ctx context.Context, req *pb.MoveCardRequest) (*pb.Card, error) {
	log.Printf("[MoveCard] card=%s -> column=%s pos=%d\n", req.CardId, req.TargetColumnId, req.TargetPosition)

	if req.CardId == "" {
		return nil, status.Error(codes.InvalidArgument, "card_id is required")
	}
	if req.TargetColumnId == "" {
		return nil, status.Error(codes.InvalidArgument, "target_column_id is required")
	}

	// Look up the board that contains this card (needed for watcher notification)
	boardID, found := s.store.FindCardBoardID(req.CardId)
	if !found {
		return nil, status.Errorf(codes.NotFound, "card %q not found", req.CardId)
	}

	card, err := s.store.MoveCard(req.CardId, req.TargetColumnId, req.TargetPosition)
	if err != nil {
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	// Notify watchers that a card was moved
	s.notifyWatchers(boardID, "card_moved")

	return card, nil
}

// ---------------------------------------------------------------------------
// DeleteCard — removes a card (unary RPC)
// ---------------------------------------------------------------------------

// DeleteCard removes a card from its board.
func (s *TaskBoardServer) DeleteCard(ctx context.Context, req *pb.DeleteCardRequest) (*pb.Empty, error) {
	log.Printf("[DeleteCard] card=%s\n", req.CardId)

	if req.CardId == "" {
		return nil, status.Error(codes.InvalidArgument, "card_id is required")
	}

	// Look up the board before deleting (needed for watcher notification)
	boardID, found := s.store.FindCardBoardID(req.CardId)
	if !found {
		return nil, status.Errorf(codes.NotFound, "card %q not found", req.CardId)
	}

	if err := s.store.DeleteCard(req.CardId); err != nil {
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	// Notify watchers that a card was deleted
	s.notifyWatchers(boardID, "card_deleted")

	return &pb.Empty{}, nil
}

// ---------------------------------------------------------------------------
// WatchBoard — server-streaming RPC for real-time updates
// ---------------------------------------------------------------------------

// WatchBoard streams BoardUpdate messages whenever the specified board changes.
// The client receives updates when cards are created, moved, or deleted.
//
// This uses a fan-out pattern: each watcher gets its own channel, and
// notifyWatchers sends to all channels for a given board.
func (s *TaskBoardServer) WatchBoard(req *pb.BoardRequest, stream pb.TaskBoardService_WatchBoardServer) error {
	log.Printf("[WatchBoard] Starting watch for board=%s\n", req.BoardId)

	// Verify the board exists
	board := s.store.GetBoard(req.BoardId)
	if board == nil {
		return status.Errorf(codes.NotFound, "board %q not found", req.BoardId)
	}

	// Create a channel for this watcher
	// Buffer size of 16 prevents slow consumers from blocking writers
	ch := make(chan *pb.BoardUpdate, 16)

	// Register the watcher
	s.watchersMu.Lock()
	s.watchers[req.BoardId] = append(s.watchers[req.BoardId], ch)
	s.watchersMu.Unlock()

	// Clean up when the stream ends (client disconnects or error)
	defer s.removeWatcher(req.BoardId, ch)

	// Send the initial board state as the first update
	initialUpdate := &pb.BoardUpdate{
		Type:  "initial",
		Board: board,
	}
	if err := stream.Send(initialUpdate); err != nil {
		return err
	}

	// Stream updates until the client disconnects
	for {
		select {
		case update, ok := <-ch:
			if !ok {
				// Channel was closed
				return nil
			}
			if err := stream.Send(update); err != nil {
				log.Printf("[WatchBoard] Send error: %v\n", err)
				return err
			}

		case <-stream.Context().Done():
			// Client disconnected or context cancelled
			log.Printf("[WatchBoard] Client disconnected for board=%s\n", req.BoardId)
			return nil
		}
	}
}

// ---------------------------------------------------------------------------
// Watcher helpers
// ---------------------------------------------------------------------------

// notifyWatchers sends a BoardUpdate to all active watchers for the given board.
func (s *TaskBoardServer) notifyWatchers(boardID, updateType string) {
	s.watchersMu.RLock()
	watchers := s.watchers[boardID]
	s.watchersMu.RUnlock()

	if len(watchers) == 0 {
		return
	}

	// Get the current board state to include in the update
	board := s.store.GetBoard(boardID)
	if board == nil {
		return
	}

	update := &pb.BoardUpdate{
		Type:  updateType,
		Board: board,
	}

	for _, ch := range watchers {
		// Non-blocking send: if the channel buffer is full, skip this watcher
		// (they're too slow and will get the next update instead)
		select {
		case ch <- update:
		default:
			log.Printf("[notifyWatchers] Watcher channel full for board=%s, skipping\n", boardID)
		}
	}
}

// removeWatcher unregisters a watcher channel for a board.
func (s *TaskBoardServer) removeWatcher(boardID string, ch chan *pb.BoardUpdate) {
	s.watchersMu.Lock()
	defer s.watchersMu.Unlock()

	watchers := s.watchers[boardID]
	for i, w := range watchers {
		if w == ch {
			s.watchers[boardID] = append(watchers[:i], watchers[i+1:]...)
			close(ch)
			break
		}
	}

	// Clean up empty watcher slices
	if len(s.watchers[boardID]) == 0 {
		delete(s.watchers, boardID)
	}

	fmt.Printf("[removeWatcher] Removed watcher for board=%s (%d remaining)\n", boardID, len(s.watchers[boardID]))
}
