// =============================================================================
// pb/taskboard.go — STUB file for generated protobuf/gRPC Go code
// =============================================================================
//
// THIS FILE IS A PLACEHOLDER. In a real project, you would NOT write this
// by hand. Instead, you would run:
//
//   protoc --go_out=. --go-grpc_out=. proto/taskboard.proto
//
// That command generates two files:
//   - pb/taskboard.pb.go        (message types, serialization)
//   - pb/taskboard_grpc.pb.go   (service interface, client/server stubs)
//
// This stub provides the minimum types and interfaces needed for the
// server code (main.go, server.go, models.go) to compile.
//
// IMPORTANT: Replace this file with the protoc-generated code before running
// in production.
// =============================================================================

package pb

import (
	"context"

	"google.golang.org/grpc"
)

// ---------------------------------------------------------------------------
// Message types (normally generated by protoc --go_out)
// ---------------------------------------------------------------------------

// Board represents a Kanban board containing multiple columns.
type Board struct {
	Id      string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Columns []*Column `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
}

// Column represents a lane in the Kanban board.
type Column struct {
	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position int32   `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	Cards    []*Card `protobuf:"bytes,4,rep,name=cards,proto3" json:"cards,omitempty"`
}

// Card represents a task item.
type Card struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ColumnId    string `protobuf:"bytes,4,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	Position    int32  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
}

// Empty is used for RPCs that don't require input or output.
type Empty struct{}

// BoardList wraps a list of boards.
type BoardList struct {
	Boards []*Board `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
}

// BoardRequest identifies a board by ID.
type BoardRequest struct {
	BoardId string `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
}

// CreateCardRequest contains data for creating a new card.
type CreateCardRequest struct {
	BoardId     string `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	ColumnId    string `protobuf:"bytes,2,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

// MoveCardRequest describes a card move operation.
type MoveCardRequest struct {
	CardId         string `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	TargetColumnId string `protobuf:"bytes,2,opt,name=target_column_id,json=targetColumnId,proto3" json:"target_column_id,omitempty"`
	TargetPosition int32  `protobuf:"varint,3,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
}

// DeleteCardRequest identifies a card to delete.
type DeleteCardRequest struct {
	CardId string `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

// BoardUpdate is streamed to clients watching a board.
type BoardUpdate struct {
	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Board *Board `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
}

// ---------------------------------------------------------------------------
// Service interface (normally generated by protoc --go-grpc_out)
// ---------------------------------------------------------------------------

// TaskBoardServiceServer is the server-side interface that must be implemented.
type TaskBoardServiceServer interface {
	GetBoards(context.Context, *Empty) (*BoardList, error)
	GetBoard(context.Context, *BoardRequest) (*Board, error)
	CreateCard(context.Context, *CreateCardRequest) (*Card, error)
	MoveCard(context.Context, *MoveCardRequest) (*Card, error)
	DeleteCard(context.Context, *DeleteCardRequest) (*Empty, error)
	WatchBoard(*BoardRequest, TaskBoardService_WatchBoardServer) error
	mustEmbedUnimplementedTaskBoardServiceServer()
}

// UnimplementedTaskBoardServiceServer provides default (unimplemented) methods.
// Embed this in your server struct for forward compatibility.
type UnimplementedTaskBoardServiceServer struct{}

func (UnimplementedTaskBoardServiceServer) GetBoards(context.Context, *Empty) (*BoardList, error) {
	return nil, nil
}
func (UnimplementedTaskBoardServiceServer) GetBoard(context.Context, *BoardRequest) (*Board, error) {
	return nil, nil
}
func (UnimplementedTaskBoardServiceServer) CreateCard(context.Context, *CreateCardRequest) (*Card, error) {
	return nil, nil
}
func (UnimplementedTaskBoardServiceServer) MoveCard(context.Context, *MoveCardRequest) (*Card, error) {
	return nil, nil
}
func (UnimplementedTaskBoardServiceServer) DeleteCard(context.Context, *DeleteCardRequest) (*Empty, error) {
	return nil, nil
}
func (UnimplementedTaskBoardServiceServer) WatchBoard(*BoardRequest, TaskBoardService_WatchBoardServer) error {
	return nil
}
func (UnimplementedTaskBoardServiceServer) mustEmbedUnimplementedTaskBoardServiceServer() {}

// ---------------------------------------------------------------------------
// Streaming interface
// ---------------------------------------------------------------------------

// TaskBoardService_WatchBoardServer is the server-side streaming interface.
type TaskBoardService_WatchBoardServer interface {
	Send(*BoardUpdate) error
	grpc.ServerStream
}

// ---------------------------------------------------------------------------
// Registration function (normally generated)
// ---------------------------------------------------------------------------

// RegisterTaskBoardServiceServer registers the service implementation with a gRPC server.
func RegisterTaskBoardServiceServer(s *grpc.Server, srv TaskBoardServiceServer) {
	// In the real generated code, this registers the service descriptor
	// and method handlers. This stub is a no-op placeholder.
	//
	// The actual generated code would look like:
	//   s.RegisterService(&_TaskBoardService_serviceDesc, srv)
	_ = s
	_ = srv
}
