// =============================================================================
// City Model — represents a searchable / favoritable city
// =============================================================================
//
// Uses @freezed for immutable data classes with value equality, copyWith, and
// JSON serialization generated by build_runner + freezed + json_serializable.
// =============================================================================

import 'package:freezed_annotation/freezed_annotation.dart';

part 'city.freezed.dart';
part 'city.g.dart';

// ---------------------------------------------------------------------------
// City data class
// ---------------------------------------------------------------------------

/// A city that can be searched for weather information.
///
/// [id] is a unique slug (e.g. "new-york"), while [name] is the display name.
/// [country] uses ISO-3166 two-letter codes (e.g. "US", "GB").
@freezed
abstract class City with _$City {
  /// Creates a [City] instance.
  const factory City({
    /// Unique identifier / slug for the city.
    required String id,

    /// Human-readable city name.
    required String name,

    /// ISO-3166 country code.
    required String country,

    /// Latitude in decimal degrees.
    required double latitude,

    /// Longitude in decimal degrees.
    required double longitude,
  }) = _City;

  /// Deserializes a [City] from a JSON map.
  factory City.fromJson(Map<String, dynamic> json) => _$CityFromJson(json);
}

// Alternative: you could use a plain Dart class with == override:
//
// class City {
//   final String id;
//   final String name;
//   ...
//   const City({required this.id, required this.name, ...});
//
//   @override
//   bool operator ==(Object other) =>
//       identical(this, other) || other is City && other.id == id;
//
//   @override
//   int get hashCode => id.hashCode;
// }
