// =============================================================================
// Hive Helper - Initialization and Box Management
// =============================================================================
//
// This file demonstrates Hive initialization patterns:
// 1. Flutter-specific initialization with hive_flutter
// 2. Type adapter registration (MUST happen before opening boxes)
// 3. Regular boxes vs lazy boxes vs encrypted boxes
// 4. Proper shutdown and cleanup
//
// Hive Architecture:
// - Data is stored in "boxes" (like tables in SQL)
// - Each box is a single file on disk
// - Boxes are loaded entirely into memory (fast reads, limited by RAM)
// - Lazy boxes load values on demand (better for large datasets)
// - Encrypted boxes use AES-256 encryption
//
// Hive vs SharedPreferences:
// - Hive: Custom types, encryption, streams, better performance
// - SharedPreferences: Simpler API, platform-native, smaller footprint
// =============================================================================

import 'dart:convert';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';

import '../../models/app_settings.dart';

// ---------------------------------------------------------------------------
// Box Name Constants
// ---------------------------------------------------------------------------

/// Box names -- using constants prevents typos and enables refactoring.
///
/// Alternative: Use an enum for box names.
class HiveBoxes {
  /// Settings box -- stores AppSettings objects
  static const String settings = 'settings';

  /// Cache box -- stores temporary data with TTL
  static const String cache = 'cache';

  /// Secure box -- encrypted storage for sensitive data
  static const String secure = 'secure_settings';
}

// ---------------------------------------------------------------------------
// Hive Helper
// ---------------------------------------------------------------------------

/// Manages Hive initialization, type adapters, and box lifecycle.
///
/// Must be initialized before any Hive operations:
/// ```dart
/// await HiveHelper.instance.initialize();
/// ```
class HiveHelper {
  HiveHelper._();

  /// Singleton instance
  static final HiveHelper instance = HiveHelper._();

  /// Whether Hive has been initialized
  bool _initialized = false;

  // ---------------------------------------------------------------------------
  // Initialization
  // ---------------------------------------------------------------------------

  /// Initializes Hive with Flutter-specific paths and type adapters.
  ///
  /// This MUST be called before any box operations.
  /// Typically called in main() before runApp().
  ///
  /// Steps:
  /// 1. Initialize Hive with app documents directory
  /// 2. Register all type adapters
  /// 3. Open commonly used boxes
  Future<void> initialize() async {
    if (_initialized) return;

    // Initialize Hive with Flutter-specific path
    // This uses path_provider internally to find the app documents directory
    await Hive.initFlutter();

    // Alternative: Initialize with a custom path
    // final dir = await getApplicationDocumentsDirectory();
    // Hive.init(dir.path);

    // Register type adapters BEFORE opening any boxes
    // The adapter ID must match the @HiveType(typeId: X) annotation
    _registerAdapters();

    _initialized = true;
  }

  /// Registers all Hive type adapters.
  ///
  /// IMPORTANT rules:
  /// 1. Register BEFORE opening boxes that contain the type
  /// 2. Each adapter's typeId must be unique (0, 1, 2, ...)
  /// 3. Never change typeIds after release (breaks existing data)
  /// 4. Order of registration doesn't matter
  void _registerAdapters() {
    // Register AppSettings adapter (generated by hive_generator)
    // TypeId 0 matches @HiveType(typeId: 0) in AppSettings
    Hive.registerAdapter(AppSettingsAdapter());

    // Alternative: Check if already registered (useful in tests)
    // if (!Hive.isAdapterRegistered(0)) {
    //   Hive.registerAdapter(AppSettingsAdapter());
    // }
  }

  // ---------------------------------------------------------------------------
  // Box Access
  // ---------------------------------------------------------------------------

  /// Opens the settings box (regular box, loaded into memory).
  ///
  /// Regular boxes load ALL data into memory on open.
  /// This is fine for small datasets like settings.
  /// For large datasets, use [openLazyBox] instead.
  Future<Box<AppSettings>> openSettingsBox() async {
    if (Hive.isBoxOpen(HiveBoxes.settings)) {
      return Hive.box<AppSettings>(HiveBoxes.settings);
    }
    return Hive.openBox<AppSettings>(HiveBoxes.settings);
  }

  /// Opens a lazy box (loads values on demand).
  ///
  /// Lazy boxes DON'T load all data into memory.
  /// Values are read from disk when accessed.
  /// Good for: large datasets, infrequently accessed data.
  ///
  /// Trade-off: Reads are async (await required) but uses less memory.
  Future<LazyBox<dynamic>> openLazyBox(String name) async {
    if (Hive.isBoxOpen(name)) {
      return Hive.lazyBox(name);
    }
    return Hive.openLazyBox(name);

    // Alternative: Open with type parameter
    // return Hive.openLazyBox<AppSettings>(name);
  }

  /// Opens an encrypted box for sensitive data.
  ///
  /// Uses AES-256 encryption. The key must be 32 bytes (256 bits).
  /// In production, store the key securely (e.g., flutter_secure_storage).
  ///
  /// WARNING: If the key is lost, the data is unrecoverable!
  Future<Box<dynamic>> openEncryptedBox() async {
    if (Hive.isBoxOpen(HiveBoxes.secure)) {
      return Hive.box(HiveBoxes.secure);
    }

    // Generate or retrieve encryption key
    // In production, use flutter_secure_storage to persist this key
    final encryptionKey = await _getEncryptionKey();

    return Hive.openBox(
      HiveBoxes.secure,
      encryptionCipher: HiveAesCipher(encryptionKey),
    );
  }

  /// Gets or generates the encryption key.
  ///
  /// In a real app, store this in platform-secure storage:
  /// - iOS: Keychain
  /// - Android: EncryptedSharedPreferences
  /// - Use flutter_secure_storage package
  Future<List<int>> _getEncryptionKey() async {
    // Check if we have a stored key
    final keyBox = await Hive.openBox('encryption_keys');
    final storedKey = keyBox.get('hive_key');

    if (storedKey != null) {
      return base64Decode(storedKey as String);
    }

    // Generate a new key (32 random bytes for AES-256)
    final key = List<int>.generate(32, (_) => Random.secure().nextInt(256));
    await keyBox.put('hive_key', base64Encode(key));

    if (kDebugMode) {
      print('[HiveHelper] Generated new encryption key');
    }

    return key;

    // Alternative: Use Hive's built-in key generation
    // final key = Hive.generateSecureKey();
    // return key;
  }

  // ---------------------------------------------------------------------------
  // Cleanup
  // ---------------------------------------------------------------------------

  /// Closes all open boxes and releases resources.
  ///
  /// Call this when the app is shutting down.
  Future<void> close() async {
    await Hive.close();
    _initialized = false;
  }

  /// Deletes a box and its data file from disk.
  ///
  /// This is permanent! Use for clearing user data on logout.
  Future<void> deleteBox(String name) async {
    if (Hive.isBoxOpen(name)) {
      final box = Hive.box(name);
      await box.close();
    }
    await Hive.deleteBoxFromDisk(name);
  }

  /// Compacts a box to reclaim disk space.
  ///
  /// Hive uses an append-only file format. Deleted/updated values
  /// leave dead space. Compaction rewrites the file without dead space.
  ///
  /// Hive auto-compacts when dead space exceeds a threshold,
  /// but you can trigger it manually if needed.
  Future<void> compactBox(String name) async {
    if (Hive.isBoxOpen(name)) {
      final box = Hive.box(name);
      await box.compact();
    }
  }
}
